### ISSUE TITLE
Enable subscribing a channel to specific notification types

### ISSUE THREAD

**Issue by acortelyou** [r-spacex/SpaceXLaunchBot#11]
eg: `slb addchannel schedule` `slb addchannel launch`

Tracking: https://github.com/r-spacex/SpaceXLaunchBot/projects/1#card-27467623

**Comment by acortelyou** [comment]
Perhaps this would be easier to implement as:

`slb [add|remove] [schedule|launch|all] [#channel|@user|@role]...`

**Comment by psidex** [comment]
Yeah I agree, that seems like the best way. I'll start work on it soon 👍

**Comment by psidex** [comment]
Just finished implementing the new notification system, will take a couple days for me to update the running bot instance but I'm going to close this now.
